# Generated by Django 5.1.5 on 2025-05-07 06:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='TextbookPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='TextbookSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_title', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WritingInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('page_id', models.IntegerField()),
                ('user_input', models.TextField()),
                ('openai_response', models.TextField()),
                ('grade', models.IntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RevisionQuestionAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed', models.DateTimeField(blank=True, null=True)),
                ('correct', models.DateTimeField(blank=True, null=True)),
                ('processed', models.BooleanField(default=False)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='engagement.revisionquestion')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_attempts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RevisionQuestionAttemptDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('processed', models.BooleanField(default=False)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='engagement.revisionquestionattempt')),
            ],
        ),
        migrations.AddField(
            model_name='revisionquestion',
            name='textbook_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rq_questions', to='engagement.textbookpage'),
        ),
        migrations.AddField(
            model_name='textbookpage',
            name='sections',
            field=models.ManyToManyField(related_name='pages', to='engagement.textbooksection'),
        ),
        migrations.CreateModel(
            name='TextbookSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_title', models.CharField(default='', max_length=200)),
                ('pages', models.ManyToManyField(related_name='slides', to='engagement.textbookpage')),
            ],
        ),
        migrations.CreateModel(
            name='UserSlideRead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_status', models.CharField(choices=[('read', 'Read'), ('unread', 'Unread'), ('revise', 'Revise')], default='unread', max_length=10)),
                ('slide', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engagement.textbookslide')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'slide')},
            },
        ),
        migrations.CreateModel(
            name='UserSlideReadSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expanded', models.DateTimeField(default=django.utils.timezone.now)),
                ('collapsed', models.DateTimeField(blank=True, null=True)),
                ('read', models.DateTimeField(blank=True, null=True)),
                ('slide_read', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_sessions', to='engagement.userslideread')),
            ],
        ),
    ]
