# Generated by Django 5.1.5 on 2025-05-25 03:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engagement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentDimension',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_pages', to='engagement.textbookpage')),
                ('sections', models.ManyToManyField(related_name='content_sections', to='engagement.textbooksection')),
            ],
        ),
        migrations.CreateModel(
            name='StudyEngagementFact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_slide_time', models.IntegerField(default=0)),
                ('slides_opened_ratio', models.FloatField(default=0.0)),
                ('first_attempt_accuracy', models.FloatField(default=0.0)),
                ('overall_accuracy', models.FloatField(default=0.0)),
                ('recall_fluency', models.FloatField(default=0.0)),
                ('total_slides', models.IntegerField(default=0)),
                ('score', models.IntegerField(default=0)),
                ('content_dim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engagement.contentdimension')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
